version: '2'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

  web:
    build: .
    command: scripts/start.sh
    ports:
      - "3000:8080"
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/tmp
    environment:
      - RAILS_ENV=development
      - MAILER_SENDER=dev@email.com
    links:
      - mysql
